show_help() {
    case $1 in
    api | x25519 | tls | run | uuid | version)
        $is_core_bin help $1 ${@:2}
        ;;
    *)
        [[ $1 ]] && warn "未知选项 '$1'"
        msg "$is_core_name script $is_sh_ver by ${display_author:-$author}"
        msg "Usage: $is_core [options]... [args]... "
        msg
        help_info=(
            "选项:"
            "   --addr, --server-addr <ip|domain>               为当前命令指定连接地址\n"
            "基本:"
            "   v, version                                      显示当前版本"
            "   ip                                              返回当前主机的 IP"
            "   pbk                                             同等于 $is_core generate reality-keypair"
            "   get-port                                        返回一个可用的端口"
            "   ss2022                                          返回一个可用于 Shadowsocks 2022 的密码\n"
            "一般:"
            "   a, add [protocol] [args... | auto]              添加配置"
            "   c, change [name] [option] [args... | auto]      更改配置"
            "   d, del [name]                                   删除配置**"
            "   i, info [name]                                  查看配置"
            "   qr [name]                                       二维码信息"
            "   url [name]                                      URL 信息"
            "   log                                             查看日志"
            # "   logerr                                          查看错误日志\n"
            "更改:"
            # "   dp, dynamicport [name] [start | auto] [end]     更改动态端口"
            "   full [name] [...]                               更改多个参数"
            "   addr [name] [ip | domain | auto]                更改连接地址"
            "   id [name] [uuid | auto]                         更改 UUID"
            "   host [name] [domain]                            更改域名"
            "   port [name] [port | auto]                       更改端口"
            "   path [name] [path | auto]                       更改路径"
            "   passwd [name] [password | auto]                 更改密码"
            "   key [name] [Private key | auto] [Public key]    更改密钥"
            # "   type [name] [type | auto]                       更改伪装类型"
            "   method [name] [method | auto]                   更改加密方式"
            "   sni [name] [ ip | domain]                       更改 serverName"
            # "   seed [name] [seed | auto]                       更改 mKCP seed"
            "   new [name] [...]                                更改协议"
            "   web [name] [domain]                             更改伪装网站\n"
            "进阶:"
            "   dns [...]                                       设置 DNS"
            "   dd, ddel [name...]                              删除多个配置**"
            "   fix [name]                                      修复一个配置"
            "   fix-all                                         修复全部配置"
            "   fix-caddyfile                                   修复 Caddyfile"
            "   fix-config.json                                 修复 config.json"
            "   import                                          导入 xray/v2ray 脚本配置\n"
            "管理:"
            "   un, uninstall                                   卸载"
            "   u, update [core | sh | caddy] [ver]             更新"
            "   U, update.sh                                    更新脚本"
            "   s, status                                       运行状态"
            "   start, stop, restart [caddy]                    启动, 停止, 重启"
            "   t, test                                         测试运行"
            "   reinstall                                       重装管理脚本\n"
            "测试:"
            # "   client, genc [name]                             显示用于客户端 JSON, 仅供参考"
            "   debug [name]                                    显示一些 debug 信息, 仅供参考"
            "   gen [...]                                       同等于 add, 但只显示 JSON 内容, 不创建文件, 测试使用"
            "   no-auto-tls [...]                               同等于 add, 但禁止自动配置 TLS, 可用于 *TLS 相关协议"
            # "   xapi [...]                                      同等于 $is_core api, 但 API 后端使用当前运行的 $is_core_name 服务\n"
            "自动化:"
            "   list, ls [filter]                               以 JSON 列出配置"
            "   inspect [name]                                  以 JSON 输出 Line 形态配置"
            "   user add|del <line> <json>                      增删某条线路的用户 (json 可含 name/uuid/password)"
            "   meta                                            重建并输出 design-15 v2 sidecar 元数据"
            "   sub                                             以 JSON 输出全部节点订阅内容"
            "   provision                                       以 JSON 检查安装与服务状态"
            "   backup [--json]                                 备份配置数据 (含 lattice-metadata.json)\n"
            "Lattice 元数据 (add/create 时读取环境变量, 写入 sidecar 而非配置文件):"
            "   LATTICE_IDENTITY_UUID   节点身份 UUID (设置后启用 sidecar 元数据)"
            "   LATTICE_NODE_ID         节点 ID"
            "   LATTICE_LINE_ID         指定线路 ID (默认自动生成并跨重建保持不变)"
            "   LATTICE_NODE_PURITY     节点纯净度 0-100 整数 (非法值仅警告并跳过)"
            "   LATTICE_NODE_QUALITY    节点质量等级 (短字符串)"
            "   身份存于 /etc/sing-box/lattice-metadata.json; 配置文件不再写入 _lattice (上游严格解析会拒绝未知字段)\n"
            "其他:"
            "   bbr                                             启用 BBR, 如果支持"
            "   bin [...]                                       运行 $is_core_name 命令, 例如: $is_core bin help"
            "   [...] [...]                                     兼容绝大多数的 $is_core_name 命令, 例如: $is_core_name generate uuid"
            "   h, help                                         显示此帮助界面\n"
        )
        for v in "${help_info[@]}"; do
            msg "$v"
        done
        msg "谨慎使用 del, ddel, 此选项会直接删除配置; 无需确认"
        msg "反馈问题) $(msg_ul https://github.com/${is_sh_repo}/issues) "
        msg "文档(doc) $(msg_ul $is_doc_url)"
        ;;

    esac
}

about() {
    msg
    msg "项目: $(msg_ul ${is_project_url:-https://github.com/${is_sh_repo}})"
    msg "文档: $(msg_ul $is_doc_url)"
    msg "反馈: $(msg_ul https://github.com/${is_sh_repo}/issues)"
    msg "Fork 来源: $(msg_ul https://github.com/${origin_repo:-233boy/sing-box})"
    msg "致谢: 感谢 233boy/sing-box 提供原始一键脚本基础"
    msg "$is_core_name site: $(msg_ul https://sing-box.sagernet.org/)"
    msg "$is_core_name core: $(msg_ul https://github.com/${is_core_repo})"
    msg
}
